#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MjljOGZjNjc1NTE0YmQzOWJjYmE3MGI0Y2IwYzAwMTA1YmE3ZTBlZWQ0ZjgyMGI3OWEwNzJmYjljYmJkN2QxY2E0ZjI0NmMyYWU1YWI0YzNjYzA5MWI3YTMxZDJjMDA4NWU1NA==
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
