apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: ghcr.io/soberich/gateway
      context: ../gateway
      jib: {}
    - image: ghcr.io/soberich/account
      context: ../account
      jib: {}
    - image: ghcr.io/soberich/transaction
      context: ../transaction
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
